image: docker:latest

services:
  - docker:dind

stages:
  - build
  - dockerize

# checkout-frontend:
#     stage: checkout
#     script:
#       - mkdir ./frontend
#       - # perform checkout

# build-frontend:
#     stage: build
#     dependencies:
#       - checkout-frontend
#     image: node:latest
#     script:
#       - cd ./frontend
#       - npm install
#       - ng build --env=prod --output-path ./../src/main/resources/static

build-backend:
  stage: build
  image: maven:3.5.3-jdk-8
  artifacts:
    paths:
      - java/target/*.jar
  script:
    - mvn clean package
  only:
    - master

dockerize:
  stage: dockerize
  dependencies:
    # - build-frontend
    - build-backend
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG"
  only:
    - master
