server.port: 9090

cors.allowed-origins:
  - http://localhost
  - http://localhost:4200
  - http://localhost:8080
  - http://fairifierfrontend
  - http://fairifierfrontend:80
  - http://fairifierfrontend:8080

fairifier:
  data-sources:

  rdf-repositories:
    server-url: http://graphdb:7200
    mapping-repository-id: mappings
    ontology-repository-id: ontologies
    data-repository-id: fair-data

swagger:
  enabled: true
  title: Fairifier API
