spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unfairdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

graphdb:
  baseUrl: http://localhost:7200/
  fairMappingDbId: fairmappingdb
  fairMappingDbTitle: FAIRMappingDb
  fairDataDbId: fairdatadb
  fairDataDbTitle: FAIRDataDb
  fairOntoDbId: fairontologydb
  fairOntoDbTitle: FAIROntologyDb

swagger:
  title: FAIRSights Fairifier
  description: Fairifier

swagger.enabled: true