cors.allowed-origins:
  - http://localhost

fairifier:
  rdf-repositories:
      server-url: http://localhost:7200
      mapping-repository-id: mappings
      ontology-repository-id: ontologies
      data-repository-id: fair-data

swagger:
  enabled: true
  title: Fairifier API
