server.port: 8080

cors.allowed-origins:
  - http://localhost
  - http://localhost:4200

fairifier:
  rdf-repositories:
      server-url: http://localhost:7200
      mapping-repository-id: mappings
      ontology-repository-id: ontologies
      data-repository-id: fair-data

swagger:
  enabled: true
  title: Fairifier API
