cors.allowed-origins:
    - http://localhost

graphdb:
  baseUrl: http://localhost:7200/
  fairMappingDbId: fairmappingdb
  fairMappingDbTitle: FAIRMappingDb
  fairDataDbId: fairdatadb
  fairDataDbTitle: FAIRDataDb
  fairOntoDbId: fairontologydb
  fairOntoDbTitle: FAIROntologyDb

swagger:
  enabled: true
  title: Fairifier API
